target 'EF_MallDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EF_MallDemo

end

platform :ios, '8.0'

pod 'Reachability',  '~> 3.0.0'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'XHImageViewer', '~> 0.1.2'
pod 'MKMapView-ZoomLevel', '~> 1.1.0'
pod 'SDWebImage', '~> 3.7.2'
pod 'libWeChatSDK', '~> 1.5'
pod "WeiboSDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk"
pod 'TencentOpenApiSDK'
pod 'MJExtension', '~> 2.5.16'
pod 'ELCImagePickerController', '~> 0.2.0'
pod 'YYModel'
#pod 'ViewMonitor', '~> 1.0.9'
pod 'MJRefresh', '~> 3.1.0’
pod 'AFNetworking', '~> 2.5.4’
pod 'FDFullscreenPopGesture', '1.1'
pod 'IQKeyboardManager', '~> 3.3.6'
pod 'SDAutoLayout', '~> 1.52'
pod 'UIScrollView+PullBig'