platform :ios  
target :EF_MallDemo do

pod 'iRate', '~> 1.11.3'
pod 'Reachability',  '~> 3.0.0'
#pod 'ZipArchive', '~> 1.3.0'

pod 'SVProgressHUD', '~> 2.0.3'
#pod 'XHImageViewer', '~> 0.1.2'
#pod 'MKMapView-ZoomLevel', '~> 1.1.0'
pod 'SDWebImage', '~> 3.7.2'
pod 'libWeChatSDK', '~> 1.5'
#pod "WeiboSDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk"
#pod 'TencentOpenApiSDK'
#pod 'JSONKit-NoWarning', '~> 1.2'
#pod 'MJExtension', '~> 2.5.16'
pod 'ELCImagePickerController', '~> 0.2.0'
pod 'YYModel'
#pod 'CocoaAsyncSocket'
#pod 'OpenSSL-Universal', '~> 1.0.1.18'
#pod 'AlipaySDK-2.0'
#pod 'JPush'
#pod 'HYBUnicodeReadable', '~> 1.1'

pod 'MJRefresh', '~> 3.1.9'
pod 'AFNetworking', '~> 3.1.0'
#pod 'UMengAnalytics-NO-IDFA'

#pod 'AMapSearch'
#pod 'AMapNavi'
#pod 'AMapLocation'
pod 'FDFullscreenPopGesture', '1.1'
pod 'IQKeyboardManager', '~> 3.3.6'
#pod 'ZXingObjC', '~> 3.1.0'
pod 'SFHFKeychainUtils', '~> 0.0.1'
pod 'SDAutoLayout', '~> 1.52'
#pod 'UIScrollView+PullBig'
#pod 'SVWebViewController', '~> 1.0'

end